"""Deterministic demo memories seeded on first launch and on RESET DEMO."""
from __future__ import annotations

SEED_MEMORIES: list[dict] = [
    {"key": "concise", "content": "Prefers concise technical explanations.",
     "category": "COMMUNICATION_STYLE", "importance": 0.95, "confidence": 0.92,
     "days_ago": 120, "related": ["examples", "devops"]},
    {"key": "examples", "content": "Likes concrete examples before detailed theory.",
     "category": "COMMUNICATION_STYLE", "importance": 0.8, "confidence": 0.85,
     "days_ago": 110, "related": ["concise"]},
    {"key": "darkmode", "content": "Prefers dark interfaces over light ones.",
     "category": "PREFERENCE", "importance": 0.7, "confidence": 0.88, "days_ago": 100,
     "related": ["terminal"]},
    {"key": "devops", "content": "Currently exploring DevOps and DevSecOps practices.",
     "category": "GOAL", "importance": 0.8, "confidence": 0.8, "days_ago": 95,
     "related": ["kubernetes", "cloud"]},
    {"key": "cloud", "content": "Building a cloud infrastructure automation project.",
     "category": "PROJECT", "importance": 0.85, "confidence": 0.85, "days_ago": 90,
     "related": ["kubernetes", "sentra", "devops"]},
    {"key": "kubernetes", "content": "Working on a Kubernetes monitoring project.",
     "category": "PROJECT", "importance": 0.9, "confidence": 0.87, "days_ago": 80,
     "related": ["cloud", "sentra"]},
    {"key": "sentra", "content": "Maintains the Sentra incident dashboard project.",
     "category": "PROJECT", "importance": 0.85, "confidence": 0.83, "days_ago": 75,
     "related": ["cloud", "nexus"]},
    {"key": "nexus", "content": "Working on NEXUS, an AI document intelligence project.",
     "category": "PROJECT", "importance": 0.85, "confidence": 0.84, "days_ago": 70,
     "related": ["sentra", "embeddings"]},
    {"key": "embeddings", "content": "Interested in local embedding models and vector search.",
     "category": "GOAL", "importance": 0.75, "confidence": 0.8, "days_ago": 65,
     "related": ["nexus", "python"]},
    {"key": "python", "content": "Uses Python as the primary backend language.",
     "category": "FACT", "importance": 0.8, "confidence": 0.9, "days_ago": 60,
     "related": ["fastapi", "typescript"]},
    {"key": "fastapi", "content": "Prefers FastAPI for building backend services.",
     "category": "PREFERENCE", "importance": 0.75, "confidence": 0.85, "days_ago": 58,
     "related": ["python"]},
    {"key": "typescript", "content": "Uses TypeScript and React on the frontend.",
     "category": "FACT", "importance": 0.75, "confidence": 0.88, "days_ago": 55,
     "related": ["python", "design"]},
    {"key": "design", "content": "Cares deeply about typography and editorial layout.",
     "category": "PREFERENCE", "importance": 0.8, "confidence": 0.82, "days_ago": 50,
     "related": ["typescript", "motion"]},
    {"key": "motion", "content": "Enjoys cinematic scroll-driven motion design.",
     "category": "PREFERENCE", "importance": 0.7, "confidence": 0.78, "days_ago": 45,
     "related": ["design"]},
    {"key": "terminal", "content": "Spends most of the working day in the terminal.",
     "category": "HABIT", "importance": 0.65, "confidence": 0.8, "days_ago": 40,
     "related": ["darkmode", "morning"]},
    {"key": "morning", "content": "Does deep technical work in the early morning.",
     "category": "HABIT", "importance": 0.6, "confidence": 0.75, "days_ago": 35,
     "related": ["terminal"]},
    {"key": "team", "content": "Works with a small platform engineering team.",
     "category": "RELATIONSHIP", "importance": 0.7, "confidence": 0.8, "days_ago": 30,
     "related": ["reviews", "kubernetes"]},
    {"key": "reviews", "content": "Reviews teammates' infrastructure pull requests weekly.",
     "category": "HABIT", "importance": 0.6, "confidence": 0.75, "days_ago": 28,
     "related": ["team"]},
    {"key": "certification", "content": "Aims to complete a Kubernetes certification this year.",
     "category": "GOAL", "importance": 0.85, "confidence": 0.8, "days_ago": 24,
     "related": ["kubernetes", "devops"]},
    {"key": "writing", "content": "Writes technical notes to consolidate new knowledge.",
     "category": "HABIT", "importance": 0.6, "confidence": 0.75, "days_ago": 20,
     "related": ["morning"]},
    {"key": "timezone", "content": "Based in the Asia/Kolkata timezone.",
     "category": "IDENTITY", "importance": 0.8, "confidence": 0.9, "days_ago": 18,
     "related": ["morning"]},
    {"key": "role", "content": "Works as a platform and infrastructure engineer.",
     "category": "IDENTITY", "importance": 0.9, "confidence": 0.9, "days_ago": 15,
     "related": ["team", "devops"]},
    {"key": "opensource", "content": "Prefers open-source and self-hostable tooling.",
     "category": "PREFERENCE", "importance": 0.8, "confidence": 0.85, "days_ago": 12,
     "related": ["embeddings", "fastapi"]},
    {"key": "latency", "content": "Cares about response latency more than model size.",
     "category": "PREFERENCE", "importance": 0.7, "confidence": 0.78, "days_ago": 8,
     "related": ["opensource"]},
]
